@BASE_URL = http://localhost:8080

### Agenda de Pacientes
GET {{BASE_URL}}/pacientes/agenda HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktand0Iiwic3ViIjoiZXUubGlyYUBwcm90b24ubWUiLCJleHAiOjE3NzE5Nzc2ODUsImlhdCI6MTc3MTk3NDA4NSwic2NvcGUiOiJST0xFX1BBQ0lFTlRFIEZBQ1RPUl9QQVNTV09SRCJ9.kuVVOLQoWZgA3Ktqpt_SpETiVrNZ8AKWnpxssdKiMf1PFES8CQ-Y1Ofg2UnwbhhpP2PuhFQqfMLpJpTuv5bULc3BvTlZCuXB67P0LqmDf_qzgSCVVFFfTv6E15hjaFtE3P_3orYag7Fnf76QeLjen9hEmPr1bwj0bqCBzVmnKHQu0iw2Gt4GENM85CZY_cxB1h49GDpV1Uf5dL5-p3oL19_LiPT7VwBwLlb_1ZgOwFEBa4oWCDxmU21kMC3Na6EvM7OYw0Xlt4pkqsLCUxVO9PUAWsVe9xFJ2x1sfcYVrqwnXeo96QVZ5ysL0jF40oNc8BD08_hcm76c4vEgqOnsVw