@BASE_URL = http://localhost:8080

### Agenda de Pacientes
GET {{BASE_URL}}/pacientes/agenda HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktand0Iiwic3ViIjoiam9hby5zaWx2YTVAZW1haWwuY29tIiwiZXhwIjoxNzcxODc3MzMxLCJpYXQiOjE3NzE4NzM3MzEsInNjb3BlIjoiUk9MRV9QQUNJRU5URSBGQUNUT1JfUEFTU1dPUkQifQ.OR2gJIny2g-WQk3g27AODdPG1_tZ724wKmpxesWvRSP-z4z1oHEoRxs-9BoO0voO4Lvd5hux4tQB4ulXdYbIAV2gAd-_o4ExqeD3xUHsZ0lJ5qm6W_f7oOcQQKY9JWrtCafC0exogiB91i43GSiICaB2kae8a15TafoUVoMYrQoqm5R2mTFkUFQyrntoBYKLz_saVVzhIaJ_NguiBZnOC8blFzQ-2ongsMLsS-FRImYC1Uiw67BAhIEuvqBgOqYP5PElZUWoz4We2XYrL5Wj4hkKn25uFqScdMwYkd1LtXxdobMK_VIS6_fzvNN0pZPb660szgYA2sCePeFZK8gYGg
