@BASE_URL = http://localhost:8080/usuarios

### Me
GET {{BASE_URL}}/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktand0Iiwic3ViIjoiZXUubGlyYUBwcm90b24ubWUiLCJleHAiOjE3NzE4ODMwMjAsImlhdCI6MTc3MTg3OTQyMCwic2NvcGUiOiJST0xFX1BBQ0lFTlRFIEZBQ1RPUl9QQVNTV09SRCJ9.ByC2ldVd6gu1Z1bWWFNfaOlOyYWkRMQsptn_RoQAPC5BsUl7kdjfJDkf5gsf3nSOstjZuzmN0YpoEDppLUi_ols32XhcSM--rKXtdrdy3dNNnCdNVMXTSEDZ0qeBI5uqkpvMupKj6_RgQJ7UUhJsRZ3vXAnaEBAKOpfsZbymmgwmqh913aLYxhB0i6NjXY25Asuj4motkWhZk-JLReHCqeFYGxKcU1u0jYDW3hhkhQGLD44kTOD4mgdsxNyrMa6a2EGSwZ7cqKXKsm0N0mZHrXBZv_omAcwFn7F7wybqVLiIu9BE9dbYe5vMxb4ynocZfR1RRGRbO4THDMYTK8C0ow