@BASE_URL = http://localhost:8080/usuarios

### Me
GET {{BASE_URL}}/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktand0Iiwic3ViIjoiam9hby5zaWx2YTVAZW1haWwuY29tIiwiZXhwIjoxNzcxODc2MjA4LCJpYXQiOjE3NzE4NzI2MDgsInNjb3BlIjoiUk9MRV9QQUNJRU5URSBGQUNUT1JfUEFTU1dPUkQifQ.ovqCMyM25vfBoM18-7S3A2cTevaihf-FdclO8MDYi6a7AeXWFUTzFNjeOZLvKWtA1Lp3Y2RC9BwYxiuJrewSfm8mc9s913a7mtKexdH9Qhs-1TCRFyusCHD3AekJNWVDOtr0KR3_q-PRsHsOdpHd7qZKWyhnQ9FMlfk-q4ZQN3ENchV_XrrjZquw9dS5xDY5kyfQ_VRMKnmkkrwqApAmVT59fyy2IK7uGQwM2O6v8oh-PHGsLWX6UlCTR3LAzvbTKrm1KUqhJTk9ad0RGouAVhzlZjeO0ujlgtLjECnyBfq_v2hihR_fNXGXw7i7F171QFZ7MdW_hc6j6_nBrOCxRg